---
- name: Converge
  hosts: all

  vars:
    ansible_user: root
    ssh_users:
      - 'testuser'
    ssh_keys_dir: 'tests/myssh_keys'

  tasks:
    - name: "Include ssh-keys"
      include_role:
        name: "ansible-role-ssh-keys"
